//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabTask.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_details
    {
        public int C_id { get; set; }
        public string C_name { get; set; }
        public string C_address { get; set; }
        public string C_phone { get; set; }
    }
}
